### ISSUE TITLE
Cannot resolve package

### ISSUE THREAD

**Issue by Traviskn** [kevinresol/react-native-sinch-verification#1]
In my MainActivity.java, I am getting build errors because com.kevinresol.sinchverification.SinchVerificationPackage is not resolved.  Everything is linked correctly, and android studio even shows react-native-sinch-verification in my project tree.  Looking at the source code of this project, I notice that the package declarations seem to incorrectly declare com.coascension when I would expect it to declare com.kevinresol.
![screen shot 2016-03-01 at 7 26 11 pm](https://cloud.githubusercontent.com/assets/3917158/13449339/8f8637b8-dfe7-11e5-858d-1a6a7a96e792.png)

Has anyone else had any issues on Android?

**Comment by kevinresol** [comment]
Probably my mistake, would you please try changing the package to `com.kevinresol`?

**Comment by kevinresol** [comment]
The strange thing is, `react-native run-android` builds successfully without error.

**Comment by Traviskn** [comment]
Yes when I change the package name to com.kevinresol, the react-native-sinch-verification package no longer builds.  But if I react-native run-android my app it ways cannot resolve symbol SinchVerificationPackage.  When I try to use autocomplete to help me out with the import in my app's MainActivity.java, it only autocompletes the R file or a *, and it can't seem to find SinchVerificationPackage.  I'm not much of an android expert so I'm not quite sure what's going on!

**Comment by kevinresol** [comment]
You need to `import com.kevinresol.sinchverification.SinchVerificationPackage;` in your MainActivity too

**Comment by Traviskn** [comment]
Yes I have import com.kevinresol.sinchverification.SinchVerificationPackage; in my MainActivity.java file, but it cannot resolve the package and when I try to run-android it gives me the cannot resolve symbol SinchVerificationPackage error

**Comment by kevinresol** [comment]
Did you change the first line of `android/src/main/java/com/kevinresol/sinchverification/SinchVerificationModule.java` and `android/src/main/java/com/kevinresol/sinchverification/SinchVerificationPackage.java` to com.kevinresol?

**Comment by Traviskn** [comment]
Yes I did change the first lines of those files

**Comment by kevinresol** [comment]
@Traviskn could you try cleaning all the builds and try again? I am not sure why, because it worked on my several machines...

**Comment by Traviskn** [comment]
@kevinresol I reinstalled the latest version of this package and cleaned the builds, everything is working fine now!  Thanks for your help
