### ISSUE TITLE
Xcode error Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by augisticz** [kevinresol/react-native-sinch-verification#2]
<img width="1478" alt="screen shot 2017-03-11 at 08 32 34" src="https://cloud.githubusercontent.com/assets/11173295/23819285/b815d5aa-0636-11e7-8a0b-9c17eb2cc63e.png">

how to fix it ?

**Comment by kevinresol** [comment]
Can you post the full linker error output?

**Comment by augisticz** [comment]
Thank you but I fixed the problem
